AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys a c7n_notifier stack including Lambda and SNS topic

Resources:
  SlackNotifierFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  SlackNotifierFunction:
    Type: AWS::Lambda::Function
    Properties:
      # deploy.sh creates lambda package in scratch prior to running cfn package
      Code: scratch/notifiers
      Handler: slack_notifier.lambda_handler
      Role: !GetAtt SlackNotifierFunctionRole.Arn
      Runtime: python3.6

  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: CloudCustodianNotifySlack
      Subscription:
        - Endpoint: !GetAtt SlackNotifierFunction.Arn
          Protocol: lambda

  SlackNotifierPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SlackNotifierFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: sns.amazonaws.com
      SourceArn: !Ref SnsTopic

Outputs:
  SnsTopicArn:
    Value: !Ref SnsTopic


